import React, { FunctionComponent, ReactNode } from 'react';
import { TextInputProps, TextProps, TextStyle, ViewProps, ViewStyle } from 'react-native';
type FormInputProps = {
    mainContainerStyle?: ViewStyle;
    inputContainerStyle?: ViewStyle;
    inputContainerBackgroundColor?: string;
    placeholderText?: string;
    placeholderTextColor?: string;
    inputStyle?: TextStyle | ViewStyle;
    inputTextColor?: string;
    hideLabel?: boolean;
    labelText?: string;
    labelTextStyle?: TextStyle;
    labelTextContainerStyle?: ViewStyle;
    isRequired?: boolean;
    requiredText?: string;
    requiredTextStyle?: TextStyle;
    requiredTextColor?: string;
    labelTextColor?: string;
    textInputProps?: TextInputProps;
    labelTextProps?: TextProps;
    requiredTextProps?: TextProps;
    mainContainerViewProps?: ViewProps;
    inputContainerViewProps?: ViewProps;
    labelTextContainerViewProps?: ViewProps;
    characterLimit?: number;
    showCharacterLimit?: boolean;
    inputType?: 'default' | 'number-pad' | 'decimal-pad' | 'numeric' | 'email-address' | 'phone-pad' | 'visible-password' | 'ascii-capable' | 'numbers-and-punctuation' | 'url' | 'name-phone-pad' | 'twitter' | 'web-search' | undefined;
    autoCapitalize?: 'none' | 'sentences' | 'words' | 'characters' | undefined;
    onTextChange?: (text: string) => void;
    value?: string;
    error?: boolean;
    errorText?: string;
    errorTextStyle?: TextStyle;
    leftIcon?: string;
    leftIconColor?: string;
    leftIconStyle?: object;
    leftIconContainerStyle?: ViewStyle;
    renderLeftIcon?: FunctionComponent<{
        children?: ReactNode;
        style?: ViewStyle;
    }>;
    leftIconOnPress?: () => void;
    rightIcon?: string;
    rightIconColor?: string;
    rightIconStyle?: object;
    rightIconContainerStyle?: ViewStyle;
    renderRightIcon?: FunctionComponent<{
        children?: ReactNode;
        style?: ViewStyle;
    }>;
    rightIconOnPress?: () => void;
    hiddenText?: boolean;
    disabled?: boolean;
    theme?: 'light' | 'dark' | 'system';
    datePicker?: boolean;
    datePickerWithTime?: boolean;
    disableFutureDates?: boolean;
    disablePastDates?: boolean;
    initialDate?: Date;
    initialRange?: {
        startDate: Date | undefined;
        endDate: Date | undefined;
    };
    initialDates?: Date[] | undefined;
    onDateChange?: (date: Date) => void;
    sendDateValue?: (dateValue: string) => void;
    onDateRangeChange?: (range: {
        startDate: Date | undefined;
        endDate: Date | undefined;
    }) => void;
    sendDateRangeValues?: (startDateValue: string, endDateValue: string) => void;
    onDatesChange?: (dates: Date[] | undefined) => void;
    sendDatesValues?: (datesValues: string[]) => void;
    datePickerBackgroundColor?: string;
    showDatePickerCloseButton?: boolean;
    datePickerCloseButtonColor?: string;
    datePickerMode?: 'single' | 'range' | 'multiple';
    selectedItemColor?: string;
    selectedTextStyle?: TextStyle;
    firstDayOfWeek?: number;
    headerTextContainerStyle?: ViewStyle;
    datePlaceholder?: string;
    datePickerAnimationType?: 'zoomIn' | 'slideUp' | 'slideDown' | 'slideLeft' | 'slideRight' | 'none';
    animationDuration?: number;
    hideDatePickerConfirmButton?: boolean;
    dateFormat?: string;
    dateTimeFormat?: string;
};
declare const FormInput: React.FC<FormInputProps>;
export default FormInput;
//# sourceMappingURL=formInput.d.ts.map