import { TextStyle, ViewStyle } from "react-native";
import { DateType } from "react-native-ui-datepicker";
export type DatePickerModalPropTypes = {
    date?: DateType;
    setDate?: (date: DateType) => void;
    range: {
        startDate: DateType;
        endDate: DateType;
    };
    setRange: (range: {
        startDate: DateType;
        endDate: DateType;
    }) => void;
    dates: DateType[] | undefined;
    setDates: (dates: Date[] | undefined) => void;
    datePickerWithTime?: boolean;
    showDatePicker?: boolean;
    setShowDatePicker: (showDatePicker: boolean) => void;
    disableFutureDates?: boolean;
    disablePastDates?: boolean;
    onDateChange?: (date: Date) => void;
    onDateRangeChange?: (range: {
        startDate: Date | undefined;
        endDate: Date | undefined;
    }) => void;
    onDatesChange?: (dates: Date[] | undefined) => void;
    datePickerBackgroundColor?: string;
    showDatePickerCloseButton?: boolean;
    datePickerCloseButtonColor?: string;
    datePickerMode?: 'single' | 'range' | 'multiple';
    firstDayOfWeek?: number;
    headerContainerStyle?: ViewStyle;
    setShowDatePlaceholder?: (showDatePlaceholder: boolean) => void;
    animationType?: 'zoomIn' | 'slideUp' | 'slideDown' | 'slideLeft' | 'slideRight' | 'none';
    animationDuration?: number;
    hideConfirmButton?: boolean;
    theme?: 'light' | 'dark' | 'system';
    selectedContainerStyle?: ViewStyle;
    selectedTextStyle?: TextStyle;
    todayContainerStyle?: ViewStyle;
    todayTextStyle?: TextStyle;
    weekDaysContainerStyle?: ViewStyle;
    weekDaysTextStyle?: TextStyle;
    yearContainerStyle?: ViewStyle;
    yearTextStyle?: TextStyle;
    activeYearContainerStyle?: ViewStyle;
    activeYearTextStyle?: TextStyle;
    selectedYearContainerStyle?: ViewStyle;
    selectedYearTextStyle?: TextStyle;
    monthContainerStyle?: ViewStyle;
    monthTextStyle?: TextStyle;
    selectedMonthContainerStyle?: ViewStyle;
    selectedMonthTextStyle?: TextStyle;
    datePickerLeftButtonStyle?: ViewStyle;
    datePickerRightButtonStyle?: ViewStyle;
    datePickerDayContainerStyle?: ViewStyle;
    datePickerDayTextStyle?: TextStyle;
    yearSelectorTextStyle?: TextStyle;
    monthSelectorTextStyle?: TextStyle;
    timeSelectorTextStyle?: TextStyle;
    datePickerOutsideDayTextStyle?: TextStyle;
    timePickerIndicatorStyle?: ViewStyle;
    datePickerRangeStyle?: ViewStyle;
    datePickerProps?: any;
    datePickerStyles?: any;
    timeTextStyle?: TextStyle;
};
//# sourceMappingURL=datePickerModalPropTypes.d.ts.map